name: testovoe_zadanie
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^7.1.0
  flutter_riverpod: ^2.3.6
  intl_utils:
  intl:
  flutter_svg: ^2.0.5
  lottie: ^2.4.0
  dio: 5.1.1
  shared_preferences: ^2.1.0
  mask_text_input_formatter: ^2.4.0
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  freezed: ^2.3.2
  #  auto_route_generator: ^7.0.0
  json_serializable: ^6.5.4
  retrofit_generator: ^6.0.0+3

flutter:
  uses-material-design: true

  assets:
    - assets/vector/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope.ttf
    - family: ManropeVariable
      fonts:
        - asset: assets/font/Manrope_VariableFont.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
